### ISSUE TITLE
clarify whether paused attribute reflects pausing of ancestor frames

### ISSUE THREAD

**Issue by dbaron** [jkarlin/pause-frame#11]
The [explainer](https://github.com/jkarlin/pause-frame) currently describes a `frameElement.paused` attribute, but isn't clear about whether this is true or false if an *ancestor* frame has been `pause()`d.  It should probably be clear about which way this works.

I think there are arguments for both sides:
* reflecting state on ancestors makes it a better source of truth
* not reflecting state from ancestors makes it correspond better to the `pause()` and `unpause()` methods.

**Comment by dbaron** [comment]
(I got here from w3ctag/design-reviews#196.)

**Comment by jkarlin** [comment]
Agreed, thanks for your comments!

Going with true if an ancestor frame was paused as that way the developer can know if it can expect a frame to do work.
