### ISSUE TITLE
Is queueing mouse events the right thing for paused frames?

### ISSUE THREAD

**Issue by bzbarsky** [jkarlin/pause-frame#17]
The explainer says that events for paused frames are queued.  As a user, I think it would be really weird if I clicked a link in a subframe, nothing happened, then sometime later the navigation randomly happened (when the frame got unpaused).

**Comment by bzbarsky** [comment]
Relatedly, it seems like the queue here could grow arbitrarily large, which also doesn't seem desirable.

**Comment by jkarlin** [comment]
I agree that this needs careful consideration. I don't think we should queue mouse events. But we probably should queue things like load events, and settimeout callbacks (though perhaps not setInterval callbacks)?This will be tricky, and likely fraught with complications.

**Comment by jkarlin** [comment]
UI Events will be discarded. The rest will be queued.
