### ISSUE TITLE
Not clear whether browsers are required to snapshot the entire paused frame

### ISSUE THREAD

**Issue by bzbarsky** [jkarlin/pause-frame#18]
If a paused frame is larger than the browser window, is the entire frame required to be snapshotted by the browser (such that scrolling the toplevel page does not need to repaint)?  Or is the expectation that scrolling would repaint (and fire rAF) in that situation?

**Comment by jkarlin** [comment]
The current thought is no snapshot required, we'd repaint and fire rAF as needed.
