### ISSUE TITLE
Should paused state be a boolean or a counter?

### ISSUE THREAD

**Issue by bzbarsky** [jkarlin/pause-frame#21]
I'm not sure what the right thing is here.  Having it be a boolean means pages that want to pause/unpause from multiple places might need to keep track of the number of pause/unpause calls themselves, out of band.  On the other hand, that does mean that it's possible to unpause no matter how many pause calls happen, if you want to do so...

This last would be particularly useful if we do want the UA to be able to unpause things that script pauses.

**Comment by jkarlin** [comment]
As of the rewrite, it returns the set of paused features. Since we don't count pause calls, it's unnecessary to return a count.
