### ISSUE TITLE
How does pausing actually work in terms of its effects on subframes of the paused frame?

### ISSUE THREAD

**Issue by bzbarsky** [jkarlin/pause-frame#23]
Say I have page A, which has frame B, which has subframe C.

If A pauses B, then pauses C, then unpauses B, is C paused?

If A pauses C, then pauses B, then unpauses B, is C paused?

If A pauses B (which pauses C, right?), then unpauses C, is C still paused?  If A then unpauses B, is C paused?

If _B_ pauses C, then A pauses B, then A unpauses B, is C paused?

This may be related to https://github.com/jkarlin/pause-frame/issues/21

**Comment by jkarlin** [comment]
Updated the explainer to address this.

The idea is that pausing increments a counter on the frame and its descendants. Unpausing decrements on the frame and its descendants.

When a counter is 0, the frame is unpaused. Else paused.

**Comment by jkarlin** [comment]
To answer your explicit questions:

> If A pauses B, then pauses C, then unpauses B, is C paused?

Yes

> If A pauses C, then pauses B, then unpauses B, is C paused?

Yes

> If A pauses B (which pauses C, right?), then unpauses C, is C still paused? If A then unpauses B, is C paused?

C is not paused. The second part of this is interesting as it causes C's counter to go negative. I *think* the appropriate response is to not allow the counter to drop below 0. 

> If B pauses C, then A pauses B, then A unpauses B, is C paused?

Yes

Leaving this issue open as it's thorny.

**Comment by bzbarsky** [comment]
OK.  What happens when the user (via the browser) wants to pause or unpause a frame?  Does that use the same counter as the web-api-exposed one, or a different counter?  That is, can a webpage unpause an iframe that a user explicitly paused?  Can a user unpause one that a webpage paused multiple times?

Back in the A, B, C case, one issue with clamping at 0 is that this sequence of actions:

* Pause B, unpause C, unpause B, pause C

has different behavior from this sequence:

* Pause B, unpause C, pause C, unpause B

but maybe that's ok.

**Comment by jkarlin** [comment]
I think the results of the different sequences are OK.

**Comment by jkarlin** [comment]
Closing this, to be reopoened as necessary.

**Comment by jkarlin** [comment]
The explainer has been updated quite a bit. And the pausing logic is much simpler now. Once a frame is paused, it will be unpaused by the next unpaused call to it or its ancestor.

So, to answer your original questions with the updates:

>Say I have page A, which has frame B, which has subframe C. If A pauses B, then pauses C, then unpauses B, is C paused?

C is not paused.

> If A pauses C, then pauses B, then unpauses B, is C paused?

C is not paused.

> If A pauses B (which pauses C, right?), then unpauses C, is C still paused?

C is not paused

> If A then unpauses B, is C paused?

C is not paused

> If B pauses C, then A pauses B, then A unpauses B, is C paused?

C is not paused.

**Comment by bzbarsky** [comment]
> Once a frame is paused, it will be unpaused by the next unpaused call to it or its ancestor.

Why is this desirable?  Seems like this means that if a page pauses some subframe, then the browser pauses the page, then the browser unpauses the page, then the subframe will suddenly be unpaused...

**Comment by jkarlin** [comment]
Ah, that was an oversimplification. See the [explainer](https://github.com/jkarlin/pause-document#pause-details) for more detail. Basically a frame can be paused by one or both of the UA and the API. But those are handled separately.

**Comment by bzbarsky** [comment]
Ah, I see.  There are pretty significant changes, and it will take me some time to think them over.
