### ISSUE TITLE
Can you pause yourself?

### ISSUE THREAD

**Issue by travisleithead** [jkarlin/pause-frame#24]
As part of review https://github.com/w3ctag/design-reviews/issues/196,

While conceptually interesting to pause yourself, this seems like a footgun. Might be worth limiting this to iframes. :-) 

Speaking of applying this feature to iframes, maybe this is better organized through [Feature Policy](https://wicg.github.io/feature-policy/)?

**Comment by travisleithead** [comment]
Guess I should read the explainer first :-) Looks like the API is already on a frame. And feature policy allows one to grant access to a feature that is blocked by default on the frame--which is not the case here. Perhaps then, this should be a new sandbox flag.

**Comment by jkarlin** [comment]
Thanks for the feedback. Are you saying you want to use some mechanism (FP or sandbox) to restrict access to the pause frame API? Or are you saying you want to use FP or sandbox to be the API?

**Comment by jkarlin** [comment]
Closing this due to lack of clarification. Please feel free to reopen!
