### ISSUE TITLE
"resource requests"

### ISSUE THREAD

**Issue by domenic** [jkarlin/pause-frame#4]
> Likewise, any resource requests generated by the frame will be queued as well, to be started upon resuming.

This doesn't really match how most resource requests work on the platform. If a resource request is generated (e.g. by fetch()), it will happen anyway. It will then queue a task to resolve the promise, or fire the event, or update the DOM, or whatever. So, when paused, no code will happen to actually process the response. But the resource request will definitely start, and even finish, despite being paused.

**Comment by jkarlin** [comment]
This needs clarification. I didn't mean that the mere act of blocking the queues would defer the resource requests. I meant the browser would, in addition to blocking queues, block resource requests.

**Comment by domenic** [comment]
Oh... that will be pretty hard to spec, I think.

**Comment by jkarlin** [comment]
Perhaps the actual queuing of the request could be inserted into the Fetch spec?

**Comment by domenic** [comment]
Yeah... I guess now that everything is centralized in fetch, it might be possible. It's worth discussing with Anne and others (including other implementers), when you feel this draft is ready to be shared more broadly. So having a tracking issue makes sense.

**Comment by jkarlin** [comment]
I'm thinking of removing the resource request bits from the explainer. If a frame is paused, how can it create network requests? Any objections?
